#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

dokku_log_action_custom() {
  declare desc="action log formatter"
  local GREEN='\033[1;32m'
  local NC='\033[0m'

  printf $"${GREEN}========> $* <========${NC}\n"
}

dokku_log_custom() {
  declare desc="basic log formatter"
  local GREEN='\033[1;32m'
  local NC='\033[0m'

  printf $"${GREEN}$*${NC}\n"
}