#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-redash-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="redash"
  local plugin_description="Quick and easy dokku based hosting for redash"

  if [[ "$CMD" == "${plugin_name}:help" ]]; then
    echo -e "Usage: dokku ${plugin_name}[:COMMAND]"
    echo ''
    echo "$plugin_description"
    echo ''
    echo 'Additional commands:'
    fn-help-content | sort | column -c2 -t -s,
  elif [[ $(ps -o command= $PPID) == *"--all"* ]]; then
    fn-help-content
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}

fn-help-content() {
  declare desc="return help content"
  cat <<help_content
    redash:create <app> <repo>, Create a Redash app from the given repo (or the official repo if none given)
    redash:destroy <app>, Destroys a Redash app and all related services
help_content
}
